name: MERN CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ matrix.envType }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env files
        run: |
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "STOCK_API_KEY=${{ secrets.DEV_STOCK_API_KEY }}" >> .env
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 📦 Install root dependencies
        run: npm install
      - name: 🔧 Backend sanity check
        working-directory: ./server
        run: |
          node server &
          sleep 5
          kill $!
      - name: 🧪 Install test dependencies
        run: |
          npm install jest
          npm install sinon
      - name: 🧪 Run unit tests
        run: npm test